<?php

use Illuminate\Database\Seeder;

class CountryListsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country_lists')->delete();

        DB::table('country_lists')->insert([
        	['id' => 1,'country' => 'Afghanistan','country_calling_code' => '93','country_currency_code' => 'AFN'    ],
			['id' => 2,'country' => 'Albania','country_calling_code' => '355','country_currency_code' => 'ALL'    ],
			['id' => 3,'country' => 'Algeria','country_calling_code' => '213','country_currency_code' => 'DZD'    ],
			['id' => 4,'country' => 'American Samoa','country_calling_code' => '684','country_currency_code' => 'USD'   ],
			['id' => 5,'country' => 'Andorra','country_calling_code' => '376','country_currency_code' => 'EUR'    ],
			['id' => 6,'country' => 'Angola','country_calling_code' => '244','country_currency_code' => 'AOA'   ],
			['id' => 7,'country' => 'Anguilla','country_calling_code' => '1-264','country_currency_code' => 'XCD'    ],
			['id' => 8,'country' => 'Antarctica','country_calling_code' => '672','country_currency_code' => 'XCD'    ],
			['id' => 9,'country' => 'Antigua and Barbuda','country_calling_code' => '1-268','country_currency_code' => 'XCD'    ],
			['id' => 10,'country' => 'Argentina','country_calling_code' => '54','country_currency_code' => 'ARS'    ],
			['id' => 11,'country' => 'Armenia','country_calling_code' => '374','country_currency_code' => 'AMD'    ],
			['id' => 12,'country' => 'Aruba','country_calling_code' => '297','country_currency_code' => 'AWG'   ],
			['id' => 13,'country' => 'Australia','country_calling_code' => '61','country_currency_code' => 'AUD'    ],
			['id' => 14,'country' => 'Austria','country_calling_code' => '43','country_currency_code' => 'EUR'    ],
			['id' => 15,'country' => 'Azerbaijan','country_calling_code' => '994','country_currency_code' => 'AZN'    ],
			['id' => 16,'country' => 'Bahamas','country_calling_code' => '1-242','country_currency_code' => 'BSD'    ],
			['id' => 17,'country' => 'Bahrain','country_calling_code' => '973','country_currency_code' => 'BHD'    ],
			['id' => 18,'country' => 'Bangladesh','country_calling_code' => '880','country_currency_code' => 'BDT'    ],
			['id' => 19,'country' => 'Barbados','country_calling_code' => '1-246','country_currency_code' => 'BBD'    ],
			['id' => 20,'country' => 'Belarus','country_calling_code' => '375','country_currency_code' => 'BYR'    ],
			['id' => 21,'country' => 'Belgium','country_calling_code' => '32','country_currency_code' => 'EUR'    ],
			['id' => 22,'country' => 'Belize','country_calling_code' => '501','country_currency_code' => 'BZD'    ],
			['id' => 23,'country' => 'Benin','country_calling_code' => '229','country_currency_code' => 'XOF'   ],
			['id' => 24,'country' => 'Bermuda','country_calling_code' => '1-441','country_currency_code' => 'BMD'    ],
			['id' => 25,'country' => 'Bhutan','country_calling_code' => '975','country_currency_code' => 'BTN'    ],
			['id' => 26,'country' => 'Bolivia','country_calling_code' => '591','country_currency_code' => 'BOB'    ],
			['id' => 27,'country' => 'Bosnia-Herzegovina','country_calling_code' => '387','country_currency_code' => 'BAM'    ],
			['id' => 28,'country' => 'Botswana','country_calling_code' => '267','country_currency_code' => 'BWP'    ],
			['id' => 29,'country' => 'Bouvet Island','country_calling_code' => '47','country_currency_code' => 'NOK'    ],
			['id' => 30,'country' => 'Brazil','country_calling_code' => '55','country_currency_code' => 'BRL'    ],
			['id' => 31,'country' => 'British Indian Ocean Territory','country_calling_code' => 246,'country_currency_code' => 'USD'    ],
			['id' => 32,'country' => 'Brunei Darussalam','country_calling_code' => '673','country_currency_code' => 'BND'    ],
			['id' => 33,'country' => 'Bulgaria','country_calling_code' => '359','country_currency_code' => 'BGN'    ],
			['id' => 34,'country' => 'Burkina Faso','country_calling_code' => '226','country_currency_code' => 'XOF'    ],
			['id' => 35,'country' => 'Burundi','country_calling_code' => '257','country_currency_code' => 'BIF'    ],
			['id' => 36,'country' => 'Cambodia','country_calling_code' => '855','country_currency_code' => 'KHR'    ],
			['id' => 37,'country' => 'Cameroon','country_calling_code' => '237','country_currency_code' => 'XAF'    ],
			['id' => 38,'country' => 'Canada','country_calling_code' => '1','country_currency_code' => 'CAD'    ],
			['id' => 39,'country' => 'Cape Verde','country_calling_code' => '238','country_currency_code' => 'CVE'    ],
			['id' => 40,'country' => 'Cayman Islands','country_calling_code' => '1-345','country_currency_code' => 'KYD'    ],
			['id' => 41,'country' => 'Central African Republic','country_calling_code' => '236','country_currency_code' => 'XAF'    ],
			['id' => 42,'country' => 'Chad','country_calling_code' => '235','country_currency_code' => 'XAF'    ],
			['id' => 43,'country' => 'Chile','country_calling_code' => '56','country_currency_code' => 'CLP'    ],
			['id' => 44,'country' => 'China','country_calling_code' => '86','country_currency_code' => 'CNY'    ],
			['id' => 45,'country' => 'Christmas Island','country_calling_code' => '61','country_currency_code' => 'AUD'    ],
			['id' => 46,'country' => 'Cocos (Keeling) Islands','country_calling_code' => '61','country_currency_code' => 'AUD'    ],
			['id' => 47,'country' => 'Colombia','country_calling_code' => '57','country_currency_code' => 'COP'    ],
			['id' => 48,'country' => 'Comoros','country_calling_code' => '269','country_currency_code' => 'KMF'    ],
			['id' => 49,'country' => 'Congo','country_calling_code' => '242','country_currency_code' => 'XAF'   ],
			['id' => 50,'country' => 'Democratic Republic of the Congo','country_calling_code' => '243','country_currency_code' => 'CDF'    ],
			['id' => 51,'country' => 'Cook Islands','country_calling_code' => '682','country_currency_code' => 'NZD'    ],
			['id' => 52,'country' => 'Costa Rica','country_calling_code' => '506','country_currency_code' => 'CRC'    ],
			['id' => 53,'country' => 'Croatia','country_calling_code' => '385','country_currency_code' => 'HRK'    ],
			['id' => 54,'country' => 'Cuba','country_calling_code' => '53','country_currency_code' => 'CUP'    ],
			['id' => 55,'country' => 'Cyprus','country_calling_code' => '357','country_currency_code' => 'EUR'    ],
			['id' => 56,'country' => 'Czech Rep.','country_calling_code' => '420','country_currency_code' => 'CZK'    ],
			['id' => 57,'country' => 'Denmark','country_calling_code' => '45','country_currency_code' => 'DKK'    ],
			['id' => 58,'country' => 'Djibouti','country_calling_code' => '253','country_currency_code' => 'DJF'    ],
			['id' => 59,'country' => 'Dominica','country_calling_code' => '1-767','country_currency_code' => 'XCD'    ],
			['id' => 60,'country' => 'Dominican Republic','country_calling_code' => '809','country_currency_code' => 'DOP'    ],
			['id' => 61,'country' => 'Ecuador','country_calling_code' => '593','country_currency_code' => 'ECS'    ],
			['id' => 62,'country' => 'Egypt','country_calling_code' => '20','country_currency_code' => 'EGP'    ],
			['id' => 63,'country' => 'El Salvador','country_calling_code' => '503','country_currency_code' => 'SVC'    ],
			['id' => 64,'country' => 'Equatorial Guinea','country_calling_code' => '240','country_currency_code' => 'XAF'    ],
			['id' => 65,'country' => 'Eritrea','country_calling_code' => '291','country_currency_code' => 'ERN'    ],
			['id' => 66,'country' => 'Estonia','country_calling_code' => '372','country_currency_code' => 'EUR'    ],
			['id' => 67,'country' => 'Ethiopia','country_calling_code' => '251','country_currency_code' => 'ETB'    ],
			['id' => 68,'country' => 'European Union','country_calling_code' => '','country_currency_code' => 'EUR'    ],
			['id' => 69,'country' => 'Falkland Islands (Malvinas)','country_calling_code' => '500','country_currency_code' => 'FKP'    ],
			['id' => 70,'country' => 'Faroe Islands','country_calling_code' => '298','country_currency_code' => 'DKK'   ],
			['id' => 71,'country' => 'Fiji','country_calling_code' => '679','country_currency_code' => 'FJD'    ],
			['id' => 72,'country' => 'Finland','country_calling_code' => '358','country_currency_code' => 'EUR'    ],
			['id' => 73,'country' => 'France','country_calling_code' => '33','country_currency_code' => 'EUR'    ],
			['id' => 74,'country' => 'French Guiana','country_calling_code' => '594','country_currency_code' => 'EUR'   ],
			['id' => 75,'country' => 'French Southern Territories','country_calling_code' => '','country_currency_code' => 'EUR'    ],
			['id' => 76,'country' => 'Gabon','country_calling_code' => '241','country_currency_code' => 'XAF'   ],
			['id' => 77,'country' => 'Gambia','country_calling_code' => '220','country_currency_code' => 'GMD'    ],
			['id' => 78,'country' => 'Georgia','country_calling_code' => '995','country_currency_code' => 'GEL'    ],
			['id' => 79,'country' => 'Germany','country_calling_code' => '49','country_currency_code' => 'EUR'    ],
			['id' => 80,'country' => 'Ghana','country_calling_code' => '233','country_currency_code' => 'GHS'   ],
			['id' => 81,'country' => 'Gibraltar','country_calling_code' => '350','country_currency_code' => 'GIP'    ],
			['id' => 82,'country' => 'Great Britain','country_calling_code' => '44','country_currency_code' => 'GBP'    ],
			['id' => 83,'country' => 'Greece','country_calling_code' => '30','country_currency_code' => 'EUR'    ],
			['id' => 84,'country' => 'Greenland','country_calling_code' => '299','country_currency_code' => 'DKK'    ],
			['id' => 85,'country' => 'Grenada','country_calling_code' => '1-473','country_currency_code' => 'XCD'    ],
			['id' => 86,'country' => 'Guadeloupe (French)','country_calling_code' => '590','country_currency_code' => 'EUR'    ],
			['id' => 87,'country' => 'Guam (USA)','country_calling_code' => '1-671','country_currency_code' => 'USD'    ],
			['id' => 88,'country' => 'Guatemala','country_calling_code' => '502','country_currency_code' => 'QTQ'    ],
			['id' => 89,'country' => 'Guernsey','country_calling_code' => '','country_currency_code' => 'GGP'    ],
			['id' => 90,'country' => 'Guinea','country_calling_code' => '224','country_currency_code' => 'GNF'    ],
			['id' => 91,'country' => 'Guinea Bissau','country_calling_code' => '245','country_currency_code' => 'GWP'   ],
			['id' => 92,'country' => 'Guyana','country_calling_code' => '592','country_currency_code' => 'GYD'    ],
			['id' => 93,'country' => 'Haiti','country_calling_code' => '509','country_currency_code' => 'HTG'   ],
			['id' => 94,'country' => 'Heard Island and McDonald Islands','country_calling_code' => '','country_currency_code' => 'AUD'    ],
			['id' => 95,'country' => 'Honduras','country_calling_code' => '504','country_currency_code' => 'HNL'    ],
			['id' => 96,'country' => 'Hong Kong','country_calling_code' => '852','country_currency_code' => 'HKD'    ],
			['id' => 97,'country' => 'Hungary','country_calling_code' => '36','country_currency_code' => 'HUF'    ],
			['id' => 98,'country' => 'Iceland','country_calling_code' => '354','country_currency_code' => 'ISK'    ],
			['id' => 99,'country' => 'India','country_calling_code' => '91','country_currency_code' => 'INR'    ],
			['id' => 100,'country' => 'Indonesia','country_calling_code' => '62','country_currency_code' => 'IDR'    ],
			['id' => 102,'country' => 'Iran','country_calling_code' => '98','country_currency_code' => 'IRR'    ],
			['id' => 103,'country' => 'Iraq','country_calling_code' => '964','country_currency_code' => 'IQD'   ],
			['id' => 104,'country' => 'Ireland','country_calling_code' => '353','country_currency_code' => 'EUR'    ],
			['id' => 105,'country' => 'Isle of Man','country_calling_code' => '','country_currency_code' => 'GBP'    ],
			['id' => 106,'country' => 'Israel','country_calling_code' => '972','country_currency_code' => 'ILS'    ],
			['id' => 107,'country' => 'Italy','country_calling_code' => '39','country_currency_code' => 'EUR'    ],
			['id' => 108,'country' => 'Ivory Coast','country_calling_code' => '225','country_currency_code' => 'XOF'    ],
			['id' => 109,'country' => 'Jamaica','country_calling_code' => '1-876','country_currency_code' => 'JMD'    ],
			['id' => 110,'country' => 'Japan','country_calling_code' => '81','country_currency_code' => 'JPY'    ],
			['id' => 111,'country' => 'Jersey','country_calling_code' => '','country_currency_code' => 'GBP'    ],
			['id' => 112,'country' => 'Jordan','country_calling_code' => '962','country_currency_code' => 'JOD'    ],
			['id' => 113,'country' => 'Kazakhstan','country_calling_code' => '7','country_currency_code' => 'KZT'    ],
			['id' => 114,'country' => 'Kenya','country_calling_code' => '254','country_currency_code' => 'KES'    ],
			['id' => 115,'country' => 'Kiribati','country_calling_code' => '686','country_currency_code' => 'AUD'    ],
			['id' => 116,'country' => 'Korea-North','country_calling_code' => '850','country_currency_code' => 'KPW'    ],
			['id' => 117,'country' => 'Korea-South','country_calling_code' => '82','country_currency_code' => 'KRW'    ],
			['id' => 118,'country' => 'Kuwait','country_calling_code' => '965','country_currency_code' => 'KWD'    ],
			['id' => 119,'country' => 'Kyrgyzstan','country_calling_code' => '996','country_currency_code' => 'KGS'    ],
			['id' => 120,'country' => 'Laos','country_calling_code' => '856','country_currency_code' => 'LAK'   ],
			['id' => 121,'country' => 'Latvia','country_calling_code' => '371','country_currency_code' => 'LVL'    ],
			['id' => 122,'country' => 'Lebanon','country_calling_code' => '961','country_currency_code' => 'LBP'    ],
			['id' => 123,'country' => 'Lesotho','country_calling_code' => '266','country_currency_code' => 'LSL'    ],
			['id' => 124,'country' => 'Liberia','country_calling_code' => '231','country_currency_code' => 'LRD'    ],
			['id' => 125,'country' => 'Libya','country_calling_code' => '218','country_currency_code' => 'LYD'    ],
			['id' => 126,'country' => 'Liechtenstein','country_calling_code' => '423','country_currency_code' => 'CHF'    ],
			['id' => 127,'country' => 'Lithuania','country_calling_code' => '370','country_currency_code' => 'LTL'    ],
			['id' => 128,'country' => 'Luxembourg','country_calling_code' => '352','country_currency_code' => 'EUR'    ],
			['id' => 129,'country' => 'Macau','country_calling_code' => '853','country_currency_code' => 'MOP'    ],
			['id' => 130,'country' => 'Macedonia','country_calling_code' => '389','country_currency_code' => 'MKD'    ],
			['id' => 131,'country' => 'Madagascar','country_calling_code' => '261','country_currency_code' => 'MGF'    ],
			['id' => 132,'country' => 'Malawi','country_calling_code' => '265','country_currency_code' => 'MWK'    ],
			['id' => 133,'country' => 'Malaysia','country_calling_code' => '60','country_currency_code' => 'MYR'    ],
			['id' => 134,'country' => 'Maldives','country_calling_code' => '960','country_currency_code' => 'MVR'    ],
			['id' => 135,'country' => 'Mali','country_calling_code' => '223','country_currency_code' => 'XOF'   ],
			['id' => 136,'country' => 'Malta','country_calling_code' => '356','country_currency_code' => 'EUR'    ],
			['id' => 137,'country' => 'Marshall Islands','country_calling_code' => '692','country_currency_code' => 'USD'    ],
			['id' => 138,'country' => 'Martinique (French)','country_calling_code' => '596','country_currency_code' => 'EUR'    ],
			['id' => 139,'country' => 'Mauritania','country_calling_code' => '222','country_currency_code' => 'MRO'    ],
			['id' => 140,'country' => 'Mauritius','country_calling_code' => '230','country_currency_code' => 'MUR'    ],
			['id' => 141,'country' => 'Mayotte','country_calling_code' => '269','country_currency_code' => 'EUR'    ],
			['id' => 142,'country' => 'Mexico','country_calling_code' => '52','country_currency_code' => 'MXN'    ],
			['id' => 143,'country' => 'Micronesia','country_calling_code' => '691','country_currency_code' => 'USD'    ],
			['id' => 144,'country' => 'Moldova','country_calling_code' => '373','country_currency_code' => 'MDL'    ],
			['id' => 145,'country' => 'Monaco','country_calling_code' => '377','country_currency_code' => 'EUR'    ],
			['id' => 146,'country' => 'Mongolia','country_calling_code' => '976','country_currency_code' => 'MNT'    ],
			['id' => 147,'country' => 'Montenegro','country_calling_code' => '382','country_currency_code' => 'EUR'    ],
			['id' => 148,'country' => 'Montserrat','country_calling_code' => '1-664','country_currency_code' => 'XCD'    ],
			['id' => 149,'country' => 'Morocco','country_calling_code' => '212','country_currency_code' => 'MAD'    ],
			['id' => 150,'country' => 'Mozambique','country_calling_code' => '258','country_currency_code' => 'MZN'    ],
			['id' => 151,'country' => 'Myanmar','country_calling_code' => '95','country_currency_code' => 'MMK'    ],
			['id' => 152,'country' => 'Namibia','country_calling_code' => '264','country_currency_code' => 'NAD'    ],
			['id' => 153,'country' => 'Nauru','country_calling_code' => '674','country_currency_code' => 'AUD'    ],
			['id' => 154,'country' => 'Nepal','country_calling_code' => '977','country_currency_code' => 'NPR'    ],
			['id' => 155,'country' => 'Netherlands','country_calling_code' => '31','country_currency_code' => 'EUR'    ],
			['id' => 156,'country' => 'Netherlands Antilles','country_calling_code' => '599','country_currency_code' => 'ANG'   ],
			['id' => 157,'country' => 'New Caledonia (French)','country_calling_code' => '687','country_currency_code' => 'XPF'    ],
			['id' => 158,'country' => 'New Zealand','country_calling_code' => '64','country_currency_code' => 'NZD'    ],
			['id' => 159,'country' => 'Nicaragua','country_calling_code' => '505','country_currency_code' => 'NIO'    ],
			['id' => 160,'country' => 'Niger','country_calling_code' => '227','country_currency_code' => 'XOF'    ],
			['id' => 161,'country' => 'Nigeria','country_calling_code' => '234','country_currency_code' => 'NGN'    ],
			['id' => 162,'country' => 'Niue','country_calling_code' => '683','country_currency_code' => 'NZD'   ],
			['id' => 163,'country' => 'Norfolk Island','country_calling_code' => '672','country_currency_code' => 'AUD'    ],
			['id' => 164,'country' => 'Northern Mariana Islands','country_calling_code' => '670','country_currency_code' => 'USD'    ],
			['id' => 165,'country' => 'Norway','country_calling_code' => '47','country_currency_code' => 'NOK'    ],
			['id' => 166,'country' => 'Oman','country_calling_code' => '968','country_currency_code' => 'OMR'   ],
			['id' => 167,'country' => 'Pakistan','country_calling_code' => '92','country_currency_code' => 'PKR'    ],
			['id' => 168,'country' => 'Palau','country_calling_code' => '680','country_currency_code' => 'USD'    ],
			['id' => 169,'country' => 'Panama','country_calling_code' => '507','country_currency_code' => 'PAB'    ],
			['id' => 170,'country' => 'Papua New Guinea','country_calling_code' => '675','country_currency_code' => 'PGK'    ],
			['id' => 171,'country' => 'Paraguay','country_calling_code' => '595','country_currency_code' => 'PYG'    ],
			['id' => 172,'country' => 'Peru','country_calling_code' => '51','country_currency_code' => 'PEN'    ],
			['id' => 173,'country' => 'Philippines','country_calling_code' => '63','country_currency_code' => 'PHP'    ],
			['id' => 174,'country' => 'Pitcairn Island','country_calling_code' => '','country_currency_code' => 'NZD'    ],
			['id' => 175,'country' => 'Poland','country_calling_code' => '48','country_currency_code' => 'PLN'    ],
			['id' => 176,'country' => 'Polynesia (French)','country_calling_code' => '689','country_currency_code' => 'XPF'    ],
			['id' => 177,'country' => 'Portugal','country_calling_code' => '351','country_currency_code' => 'EUR'    ],
			['id' => 178,'country' => 'Puerto Rico','country_calling_code' => '1-787','country_currency_code' => 'USD'    ],
			['id' => 179,'country' => 'Qatar','country_calling_code' => '974','country_currency_code' => 'QAR'    ],
			['id' => 180,'country' => 'Reunion (French)','country_calling_code' => '262','country_currency_code' => 'EUR'    ],
			['id' => 181,'country' => 'Romania','country_calling_code' => '40','country_currency_code' => 'RON'    ],
			['id' => 182,'country' => 'Russia','country_calling_code' => '7','country_currency_code' => 'RUB'    ],
			['id' => 183,'country' => 'Rwanda','country_calling_code' => '250','country_currency_code' => 'RWF'    ],
			['id' => 184,'country' => 'Saint Helena','country_calling_code' => '290','country_currency_code' => 'SHP'   ],
			['id' => 185,'country' => 'Saint Kitts & Nevis Anguilla','country_calling_code' => '1-869','country_currency_code' => 'XCD' ],
			['id' => 186,'country' => 'Saint Lucia','country_calling_code' => '1-758','country_currency_code' => 'XCD'    ],
			['id' => 187,'country' => 'Saint Pierre and Miquelon','country_calling_code' => '508','country_currency_code' => 'EUR'    ],
			['id' => 188,'country' => 'Saint Vincent & Grenadines','country_calling_code' => '1-784','country_currency_code' => 'XCD'    ],
			['id' => 189,'country' => 'Samoa','country_calling_code' => '684','country_currency_code' => 'WST'    ],
			['id' => 190,'country' => 'San Marino','country_calling_code' => '378','country_currency_code' => 'EUR'    ],
			['id' => 191,'country' => 'Sao Tome and Principe','country_calling_code' => '239','country_currency_code' => 'STD'    ],
			['id' => 192,'country' => 'Saudi Arabia','country_calling_code' => '966','country_currency_code' => 'SAR'   ],
			['id' => 193,'country' => 'Senegal','country_calling_code' => '221','country_currency_code' => 'XOF'    ],
			['id' => 194,'country' => 'Serbia','country_calling_code' => '381','country_currency_code' => 'RSD'    ],
			['id' => 195,'country' => 'Seychelles','country_calling_code' => '248','country_currency_code' => 'SCR'    ],
			['id' => 196,'country' => 'Sierra Leone','country_calling_code' => '232','country_currency_code' => 'SLL'   ],
			['id' => 197,'country' => 'Singapore','country_calling_code' => '65','country_currency_code' => 'SGD'    ],
			['id' => 198,'country' => 'Slovakia','country_calling_code' => '421','country_currency_code' => 'EUR'    ],
			['id' => 199,'country' => 'Slovenia','country_calling_code' => '386','country_currency_code' => 'EUR'    ],
			['id' => 200,'country' => 'Solomon Islands','country_calling_code' => '677','country_currency_code' => 'SBD'    ],
			['id' => 201,'country' => 'Somalia','country_calling_code' => '252','country_currency_code' => 'SOS'    ],
			['id' => 202,'country' => 'South Africa','country_calling_code' => '27','country_currency_code' => 'ZAR'    ],
			['id' => 203,'country' => 'South Georgia & South Sandwich Islands','country_calling_code' => '','country_currency_code' => 'GBP'    ],
			['id' => 204,'country' => 'South Sudan','country_calling_code' => '','country_currency_code' => 'SSP'    ],
			['id' => 205,'country' => 'Spain','country_calling_code' => '34','country_currency_code' => 'EUR'    ],
			['id' => 206,'country' => 'Sri Lanka','country_calling_code' => '94','country_currency_code' => 'LKR'    ],
			['id' => 207,'country' => 'Sudan','country_calling_code' => '249','country_currency_code' => 'SDG'    ],
			['id' => 208,'country' => 'Suriname','country_calling_code' => '597','country_currency_code' => 'SRD'    ],
			['id' => 209,'country' => 'Svalbard and Jan Mayen Islands','country_calling_code' => '','country_currency_code' => 'NOK'    ],
			['id' => 210,'country' => 'Swaziland','country_calling_code' => '268','country_currency_code' => 'SZL'    ],
			['id' => 211,'country' => 'Sweden','country_calling_code' => '46','country_currency_code' => 'SEK'    ],
			['id' => 212,'country' => 'Switzerland','country_calling_code' => '41','country_currency_code' => 'CHF'    ],
			['id' => 213,'country' => 'Syria','country_calling_code' => '963','country_currency_code' => 'SYP'    ],
			['id' => 214,'country' => 'Taiwan','country_calling_code' => '886','country_currency_code' => 'TWD'    ],
			['id' => 215,'country' => 'Tajikistan','country_calling_code' => '992','country_currency_code' => 'TJS'    ],
			['id' => 216,'country' => 'Tanzania','country_calling_code' => '255','country_currency_code' => 'TZS'    ],
			['id' => 217,'country' => 'Thailand','country_calling_code' => '66','country_currency_code' => 'THB'    ],
			['id' => 218,'country' => 'Togo','country_calling_code' => '228','country_currency_code' => 'XOF'   ],
			['id' => 219,'country' => 'Tokelau','country_calling_code' => '690','country_currency_code' => 'NZD'    ],
			['id' => 220,'country' => 'Tonga','country_calling_code' => '676','country_currency_code' => 'TOP'    ],
			['id' => 221,'country' => 'Trinidad and Tobago','country_calling_code' => '1-868','country_currency_code' => 'TTD'    ],
			['id' => 222,'country' => 'Tunisia','country_calling_code' => '216','country_currency_code' => 'TND'    ],
			['id' => 223,'country' => 'Turkey','country_calling_code' => '90','country_currency_code' => 'TRY'    ],
			['id' => 224,'country' => 'Turkmenistan','country_calling_code' => '993','country_currency_code' => 'TMT'   ],
			['id' => 225,'country' => 'Turks and Caicos Islands','country_calling_code' => '1-649','country_currency_code' => 'USD'    ],
			['id' => 226,'country' => 'Tuvalu','country_calling_code' => '688','country_currency_code' => 'AUD'    ],
			['id' => 227,'country' => 'United Kingdom','country_calling_code' => '44','country_currency_code' => 'GBP'    ],
			['id' => 228,'country' => 'United States','country_calling_code' => '1','country_currency_code' => 'USD'    ],
			['id' => 229,'country' => 'USA Minor Outlying Islands','country_calling_code' => '','country_currency_code' => 'USD'    ],
			['id' => 230,'country' => 'Uganda','country_calling_code' => '256','country_currency_code' => 'UGX'    ],
			['id' => 231,'country' => 'Ukraine','country_calling_code' => '380','country_currency_code' => 'UAH'    ],
			['id' => 232,'country' => 'United Arab Emirates','country_calling_code' => '971','country_currency_code' => 'AED'   ],
			['id' => 233,'country' => 'Uruguay','country_calling_code' => '598','country_currency_code' => 'UYU'    ],
			['id' => 234,'country' => 'Uzbekistan','country_calling_code' => '998','country_currency_code' => 'UZS'    ],
			['id' => 235,'country' => 'Vanuatu','country_calling_code' => '678','country_currency_code' => 'VUV'    ],
			['id' => 236,'country' => 'Vatican','country_calling_code' => '39','country_currency_code' => 'EUR'    ],
			['id' => 237,'country' => 'Venezuela','country_calling_code' => '58','country_currency_code' => 'VEF'    ],
			['id' => 238,'country' => 'Vietnam','country_calling_code' => '84','country_currency_code' => 'VND'    ],
			['id' => 239,'country' => 'Virgin Islands (British)','country_calling_code' => '1-284','country_currency_code' => 'USD'    ],
			['id' => 240,'country' => 'Virgin Islands (USA)','country_calling_code' => '1-340','country_currency_code' => 'USD' ],
			['id' => 241,'country' => 'Wallis and Futuna Islands','country_calling_code' => '681','country_currency_code' => 'XPF'    ],
			['id' => 242,'country' => 'Western Sahara','country_calling_code' => '','country_currency_code' => 'MAD'    ],
			['id' => 243,'country' => 'Yemen','country_calling_code' => '967','country_currency_code' => 'YER'    ],
			['id' => 244,'country' => 'Zambia','country_calling_code' => '260','country_currency_code' => 'ZMW'    ],
			['id' => 245,'country' => 'Zimbabwe','country_calling_code' => '263','country_currency_code' => 'ZWD'    ]]);
    }
}
